### ISSUE TITLE
perldoc-jp/translation リポジトリへの統合を行いたい 

### ISSUE THREAD

**Issue by kfly8** [jpa/MooseX-Getopt-Doc-JA#1]
次のIssueと同様の主旨の確認をしたいです。いかがでしょうか？ @lestrrat 

https://github.com/jpa/Moose-Doc-JA/issues/1

**Comment by lestrrat** [comment]
あちらと同じで問題ないですー

**Comment by kfly8** [comment]
マージ作業します！

**Comment by kfly8** [comment]
次のPRでマージしました！

https://github.com/perldoc-jp/translation/pull/109
